### ISSUE TITLE
Step Specific Env

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#234]
By specifying environment variables on a per-step basis, the maintainability of workflows can be greatly improved. For instance, the following YAML snippet sets the FOO environment variable to "BAR" for task1:

```yaml
env:
  - FOO: "BAR"
steps:
  - name: task1
    env:
      - FOO: "BAR-TASK1"
    command: echo $FOO # "BAR-TASK1" will be printed in the log
```
