### ISSUE TITLE
Add support for user-defined functions and call field in YAML format

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#429]
Add support for defining user-defined functions and a `call` field in the YAML format to enable more modular and reusable code within the DAGs.

Introduce a new top-level `functions` field for defining user-defined functions, and a new `call` field within the `steps` section to call those functions.

Example of defining a function and calling a function:

```yaml
functions:
  - name: my_function
    params: param1 param2
    command: python main.py $param1 $param2

steps:
  - name: step 1
    call:
      function: my_function
      args:
        param1: 1
        param2: 2
```
