### ISSUE TITLE
Schedule ETL Tasks using Meltano

### ISSUE THREAD

**Issue by rajasekhar-gundala** [dagu-dev/dagu#434]
Hell Team,
Thank you very much for the project. is there any way to integrate [Meltano](https://meltano.com/) ETL Pipelines with this tool?

**Comment by yohamta** [comment]
Hello @rajaseg, it's great to hear that you're interested in integrating Meltano ETL Pipelines with Dagu! Yes, you can easily achieve this by creating a DAG to call Meltano commands.

Here's an example:
```yaml
schedule: "0 0 * * *"
steps:
  - name: myStep
    command: meltano elt tap-extractor target-loader
```

You can customize this example to fit your needs by adding more steps or modifying the existing ones. If you have any further questions or need any help, please don't hesitate to ask.

**Comment by rajaseg** [comment]
@yohamta I got below error when I try to run Dagu using docker-compose

> ! dagu The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested

#### docker-compose.yaml
```
version: "3.7"

services:
  dagu:
    image: yohamta/dagu:latest
    restart: unless-stopped
    ports:
      - "8000:8080"
    networks:
      - caddy
    volumes:
      - ./dagu-dags:/home/dagu/.dagu/dags
      - ./dagu-data:/home/dagu/.dagu/data
      - ./dagu-logs:/home/dagu/.dagu/logs
volumes:
  dagudags:
  dagudata:
  dagulogs:
networks:
  caddy:
    external: true
```
After some research I have included ```platform: linux/arm64``` entry in ```docker-compose```
I got below error after the platform entry

> exec /bin/sh: exec format error

Am I doing anything wrong?

**Comment by yohamta** [comment]
Hey @rajaseg ! I'd recommend giving the following Docker image a try: `yohamta/dagu:1.10.4-amd64` or `yohamta/dagu:latest-amd64`. It should work well for your system.

**Comment by rajaseg** [comment]
> Hey @rajaseg ! I'd recommend giving the following Docker image a try: `yohamta/dagu:1.10.4-amd64` or `yohamta/dagu:latest-amd64`. It should work well for your system.

Hi @yohamta, when I use ```yohamta/dagu:latest-amd64``` got the below error message

> Error response from daemon: manifest for yohamta/dagu:latest-amd64 not found: manifest unknown: manifest unknown

When I use ```yohamta/dagu:1.10.4-amd64``` got below error message

> Error response from daemon: image with reference yohamta/dagu:1.10.4-amd64 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8

**Comment by yohamta** [comment]
Hi @rajaseg , thanks for providing all the details.

Could you please give it another shot? Also, kindly double-check that your docker-compose file doesn't have platform: `linux/arm64` in it.

Here are the commands to run:
```sh
docker image rm yohamta/dagu:latest-amd64
docker image rm yohamta/dagu:1.10.4-amd64
docker-compose up
```

**Comment by yohamta** [comment]
Hi @rajaseg , that's a bit strange!

Would you mind checking if any of the binaries from the link below work on your PC?

https://github.com/yohamta/dagu/releases/tag/v1.10.4

Just download the appropriate binary and give it a try with this command: `./dagu server --port=8000`

Let me know how it goes!

**Comment by rajaseg** [comment]
> Hi @rajaseg , that's a bit strange!
> 
> Would you mind checking if any of the binaries from the link below work on your PC?
> 
> https://github.com/yohamta/dagu/releases/tag/v1.10.4
> 
> Just download the appropriate binary and give it a try with this command: `./dagu server --port=8000`
> 
> Let me know how it goes!

Hi @yohamta Please find the outcome below.

![image](https://user-images.githubusercontent.com/633479/232673332-fc7ffc79-a097-4a03-a0aa-cf621ebca709.png)

**Comment by yohamta** [comment]
Hey @rajaseg, great to hear that it's working on your computer!
Could you please let us know which binary you used?

- [dagu_1.10.4_Darwin_arm64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Darwin_arm64.tar.gz)
- [dagu_1.10.4_Darwin_x86_64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Darwin_x86_64.tar.gz)
- [dagu_1.10.4_Linux_arm64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_arm64.tar.gz)
- [dagu_1.10.4_Linux_armv7.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_armv7.tar.gz)
- [dagu_1.10.4_Linux_x86_64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_x86_64.tar.gz)

I can build a docker image for that binary.

**Comment by rajaseg** [comment]
> Hey @rajaseg, great to hear that it's working on your computer! Could you please let us know which binary you used?
> 
> * [dagu_1.10.4_Darwin_arm64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Darwin_arm64.tar.gz)
> * [dagu_1.10.4_Darwin_x86_64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Darwin_x86_64.tar.gz)
> * [dagu_1.10.4_Linux_arm64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_arm64.tar.gz)
> * [dagu_1.10.4_Linux_armv7.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_armv7.tar.gz)
> * [dagu_1.10.4_Linux_x86_64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_x86_64.tar.gz)
> 
> I can build a docker image for that binary.

Hi @yohamta I have used ```[dagu_1.10.4_Linux_x86_64.tar.gz](https://github.com/dagu-labs/dagu/releases/download/v1.10.4/dagu_1.10.4_Linux_x86_64.tar.gz)```

**Comment by yohamta** [comment]
Hey @rajaseg, I appreciate the extra info you provided!
I've figured out the issue and have rebuilt the most recent image.

Could you kindly give `yohamta/dagu:latest` a try instead of `yohamta/dagu:latest-amd64` ? Here are the steps:
```sh
docker image rm yohamta/dagu:latest
docker image rm yohamta/dagu:1.10.4
docker-compose up
```

I believe it should work now! Take care and have a great day!

**Comment by rajaseg** [comment]
> Hey @rajaseg, I appreciate the extra info you provided! I've figured out the issue and have rebuilt the most recent image.
> 
> Could you kindly give `yohamta/dagu:latest` a try instead of `yohamta/dagu:latest-amd64` ? Here are the steps:
> 
> ```shell
> docker image rm yohamta/dagu:latest
> docker image rm yohamta/dagu:1.10.4
> docker-compose up
> ```
> 
> I believe it should work now! Take care and have a great day!

Hi @yohamta I tried with ```yohamta/dagu:latest``` but no luck. ```docker logs dagu``` gives me the below error.

> exec /bin/sh: exec format error

**Comment by yohamta** [comment]
Hey @rajaseg, would you mind providing me with the output of the following command?

```sh
docker image inspect yohamta/dagu:latest | grep -A2 Architecture
```

Also, can you please try using the `platform: linux/amd64` parameter? Here's the updated docker-compose file with the `platform: linux/amd64` parameter added:

```yaml
version: "3.7"

services:
  dagu:
    platform: linux/amd64
    image: yohamta/dagu:latest
    restart: unless-stopped
    ports:
      - "8000:8080"
    networks:
      - caddy
    volumes:
      - ./dagu-dags:/home/dagu/.dagu/dags
      - ./dagu-data:/home/dagu/.dagu/data
      - ./dagu-logs:/home/dagu/.dagu/logs
volumes:
  dagudags:
  dagudata:
  dagulogs:
networks:
  caddy:
    external: true
```

Please make sure to remove the image before running docker-compose with these changes:

```sh
docker image rm yohamta/dagu:latest
docker image rm yohamta/dagu:1.10.4
docker-compose up
```

Thanks a lot for your help!
