### ISSUE TITLE
Add Slack Integration for Workflow Notification and Executor

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#441]
This will allow users to receive real-time updates on the status of their DAGs directly in their preferred Slack channels.

Here is the suggested configuration for enabling Slack notification within a DAG:
```yaml
notification:
  - provider: Slack
    token: $SLACK_AUTH_TOKEN
    channel: $SLACK_CHANNEL
    on:
      failure: true
      success: true
```

In addition to notifications, we can also introduce `slack` executor:
```yaml
steps:
  - name: s1
    executor:
      type: slack
      config:
        token: $SLACK_AUTH_TOKEN
        channel: $SLACK_CHANNEL
    script: "hello"
```

By implementing this feature, we can improve the user experience by providing real-time updates on DAG execution and streamline communication within teams. It will also open up the possibility for further integrations with other messaging platforms in the future.
