### ISSUE TITLE
Precondition Bash Script Errors

### ISSUE THREAD

**Issue by mnmercer** [dagu-dev/dagu#453]
I am trying to have a precondition on a step that checks to be sure that the output of the previous step actually has a value set with a simple one liner bash script. However, when I add the script in as my `condition`, the DAG errors with 
```
failed to evaluate condition. Condition=`[[ ! -z '$DATASET_DEF' ]] && echo 'Not empty' || echo 'Empty'` Error=exec: "[[": executable file not found in $PATH
```
The precondition looks like this
```yaml
    preconditions:
      - condition: "`[[ ! -z '$DATASET_DEF' ]] && echo 'Not empty' || echo 'Empty'`"
        expected: "Not empty"
```
What exactly is supported between the backticks? The documentation and examples don't really make it clear.
