### ISSUE TITLE
Intentionally Fail a DAG

### ISSUE THREAD

**Issue by mnmercer** [dagu-dev/dagu#455]
Maybe I'm just missing something in the documentation, but my use case is that I want there to be a check in my DAG for a specific condition and if that condition fails, for the whole DAG to be marked as a failure. The `preconditions` attribute on the steps helps with the first part of only executing when a condition is satisfied, but I'm having trouble figuring out how to then mark the DAG as a failure. If I simply check for the positive condition and it comes back as negative, the rest of the steps don't execute, but the DAG is marked as finished successfully. I tried adding a branch for the negative condition, but I can't figure out how to make the DAG show as failed. I thought setting the `signalOnStop` for the negative condition step to something like "SIGQUIT" would do it, but it still comes through as "finished".
A simple DAG to reproduce looks like this.
```yaml
params: foo
steps:
  - name: step1
    command: "echo $1"
  - name: positive case
    depends:
      - step1
    preconditions:
      - condition: "$1"
        expected: "foo"
    command: "echo 'Success'"
  - name: negative case
    depends:
      - step1
    preconditions:
      - condition: "$1"
        expected: "bar"
    command: "echo 'Failure'"
    signalOnStop: "SIGQUIT"
```

**Comment by ghansham** [comment]
In the negative case, return a non zero value. The step will be marked failed and so will be dag.

**Comment by mnmercer** [comment]
@ghansham I tried running a DAG like this and in the negative case, it is still marking the step and DAG as a success instead of a failure. Am I misunderstanding what you are referring to?
```yaml
params: foo
steps:
  - name: step1
    command: "echo $1"
  - name: positive case
    depends:
      - step1
    preconditions:
      - condition: "$1"
        expected: "foo"
    command: "echo 'Success'"
  - name: negative case
    depends:
      - step1
    preconditions:
      - condition: "$1"
        expected: "bar"
    command: "echo 'Failure' && exit 1"
```
