### ISSUE TITLE
Running scheduled dag

### ISSUE THREAD

**Issue by seos-vcbs** [dagu-dev/dagu#461]
Dag version: 1.10.2

I have dags that run at specific time. They all run fine. However, if I was to change the scheduled time the updated dag does not get executed. Here is the snippet of the dag. I can see the next run counting down to 0. I expected my dag to run but nothing happens.

```
schedule: "55 15 * * *"
steps:
  - name: test
    command: date
```

my dags that are set to run at "0 9 * * *" are fine.

Am I doing something wrong?
