### ISSUE TITLE
不支持重定向吗?

### ISSUE THREAD

**Issue by JuchangGit** [dagu-dev/dagu#492]
steps:
  - name: hello
    command: "echo 000 > /opt/seatunnel/job/test1"

只是执行了echo 000  ，没有将000写入/opt/seatunnel/job/test1文件

**Comment by yohamta** [comment]
Hay, it seems you've already found out, but just wanted to share just in case.
You can use `output` field for redirection to any file. Here's an example.
```yaml
steps:
  - name: step 1
    command: "echo foo"
    output: FOO # will contain "foo"
```
