### ISSUE TITLE
Add log output to mail

### ISSUE THREAD

**Issue by triole** [dagu-dev/dagu#493]
For debugging it would be really helpful if there was a possibility to add the dag's log to a sent mail. Having a mail with information like this in your inbox would give a more helpful first impression of what exactly went wrong. So that you could immediately estimate how much effort would be needed for debugging to decide if when there is time to look deeper into it. Maybe we could have an option to attach the logs as file to the mail and then have it sent. Something like...

```
errorMail:
  from: "mob@5x2.de"
  to: "mob@5x2.de"
  prefix: "[Error]"
  attachLogs: true
```
