### ISSUE TITLE
K3s internal deployment error

### ISSUE THREAD

**Issue by nnn149** [dagu-dev/dagu#504]
container log: standard_init_linux.go:228: exec user process caused: exec format error

```yaml

kind: Pod
apiVersion: v1
metadata:
  name: dagu-0
  generateName: dagu-
  namespace: yhy
  labels:
    app: dagu
    controller-revision-hash: dagu-7f9bf9869c
    statefulset.kubernetes.io/pod-name: dagu-0
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/imagepullsecrets: '{}'
    logging.kubesphere.io/logsidecar-config: '{}'
spec:
  volumes:
    - name: host-time
      hostPath:
        path: /etc/localtime
        type: ''
    - name: dagu-dags
      hostPath:
        path: /mnt/disks1/dagu/dags
        type: ''
    - name: dagu-data
      hostPath:
        path: /mnt/disks1/dagu/data
        type: ''
    - name: dagu-logs
      hostPath:
        path: /mnt/disks1/dagu/logs
        type: ''
    - name: kube-api-access-b4bwb
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: container-dagu
      image: 'yohamta/dagu:latest'
      ports:
        - name: tcp-8080
          containerPort: 8080
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: host-time
          readOnly: true
          mountPath: /etc/localtime
        - name: dagu-dags
          mountPath: /home/dagu/.dagu/dags
        - name: dagu-data
          mountPath: /home/dagu/.dagu/data
        - name: dagu-logs
          mountPath: /home/dagu/.dagu/logs
        - name: kube-api-access-b4bwb
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: izwz97xejdyxxf7cixkijdz
  securityContext: {}
  hostname: dagu-0
  subdomain: dagu-uzdb
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority


```
