### ISSUE TITLE
Cannot parse named params

### ISSUE THREAD

**Issue by anishjain94** [dagu-dev/dagu#563]
I am not able to add named params. It gives the following error. Attaching workflow config file for referece. what am i doing wrong here. can somebody help me please.

```name: invoice_generation
description: invoice_generation
schedule: '0 3 4 * *'
group: user
tags: user

histRetentionDays: 1
maxActiveRuns: 1
delaySec: 1
MaxCleanUpTimeSec: 5000
logDir: /home/dagu/logs/dags
params: "invoice_date=2024-05-05"

steps:
  - name: INVOICE_NUMBER_GENERATION
    description: Invoice number generation
    command: /home/dagu/bin/cron INVOICE_NUMBER_GENERATION ${invoice_date}
    signalOnStop: 'SIGINT'
  - name: INVOICE_DATA_POPULATION
    description: Invoice data population
    command: /home/dagu/bin/cron INVOICE_DATA_POPULATION ${invoice_date}
    signalOnStop: 'SIGINT'
    depends:
      - INVOICE_NUMBER_GENERATION
  - name: INVOICE_IRN_GENERATION
    description: Invoice IRN generation
    command: /home/dagu/bin/cron INVOICE_IRN_GENERATION ${invoice_date}
    signalOnStop: 'SIGINT'
    depends:
      - INVOICE_DATA_POPULATION
```

<img width="778" alt="Screenshot 2024-05-08 at 16 25 47" src="https://github.com/dagu-dev/dagu/assets/25664697/bc1cc037-92ac-48c9-a8ed-dea4aeee54bf">

**Comment by yohamta** [comment]
Hello, 

I just have tried it and it seems working fine on my environment with the configuration:

```yaml
description: invoice_generation
schedule: '0 3 4 * *'
group: user
tags: user

histRetentionDays: 1
maxActiveRuns: 1
delaySec: 1
MaxCleanUpTimeSec: 5000
params: "invoice_date=2024-05-05"

steps:
  - name: INVOICE_NUMBER_GENERATION
    description: Invoice number generation
    command: echo ${invoice_date}
    signalOnStop: 'SIGINT'
  - name: INVOICE_DATA_POPULATION
    description: Invoice data population
    command: echo ${invoice_date}
    signalOnStop: 'SIGINT'
    depends:
      - INVOICE_NUMBER_GENERATION
  - name: INVOICE_IRN_GENERATION
    description: Invoice IRN generation
    command: echo ${invoice_date}
    signalOnStop: 'SIGINT'
    depends:
      - INVOICE_DATA_POPULATION
```

<img width="860" alt="image" src="https://github.com/dagu-dev/dagu/assets/1475839/f9888fe7-a03a-4986-814d-49061da13c01">
