### ISSUE TITLE
Add Built-in Execution Context Variables

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#581]
**Overview**
Introduce built-in execution context variables for each DAG execution.

**Variables**
- `DAGU_LOCAL_SCHEDULER_LOG_PATH`
- `DAGU_LOCAL_EXECUTION_LOG_PATH`
- `DAGU_LOCAL_REQUEST_ID`

**Example Usage**
```yaml
handlerOn:
  failure:
    command: "echo There was an error while doing ${DAG_REQUEST_ID} request"
```

**Additional Context**
- #552
