### ISSUE TITLE
(ux) Long params in yaml template lead to being unable to Start and click Confirm

### ISSUE THREAD

**Issue by zph** [dagu-dev/dagu#594]
Reproduction case:

create hello-world.yaml and set params key to something with ~2500 characters.

Then try to start the dag from UI. The confirmation box's "Confirm" button is pushed off screen and inaccessible.

Possible solutions:
1. make the text inputs scrollable
2. rework design to have wider confirmation popup (may not be enough)

There's a related ui degradation also caused in this case on the dag show view, where long params cause the Dag Row to be very tall, so it requires scrolling down for clicking the logs button.

Is this a real problem?

For me it is :). I'm injecting long params so I can use them as env vars in the commands. Think of things like presigned aws links or a long list of a PATH var.

I'm happy to do the fixes but want to align on approach first to avoid rework 🌟 

Let me know what you think @yohamta

**Comment by yohamta** [comment]
Hi @zph,
Thank you for the detailed description of the issue. I agree this is indeed a problem we should address. We'll probably need to implement both solutions (1 and 2), but I'm open to other approaches as well. 

I attempted to reproduce the issue on my end, but I may have done something incorrectly as I couldn't replicate the problem. Could you please confirm if my reproduction steps were correct? Here's the YAML I used:

Here's the YAML I used:
```yaml
params: "VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER=default-value"
steps:
  - name: step1
    command: echo hello

```

Popup on 'Start' button:
<img width="854" alt="image" src="https://github.com/dagu-dev/dagu/assets/1475839/1c4beb32-4637-437e-a7bb-982c56f377da">

**Comment by zph** [comment]
@yohamta Ah, I was not specific enough. My apology 😄 .

If the value in the key value pair is overly long, then it has the defect. I hadn't tried a very long key in the k/v pair.

Example of problem:

<img width="1241" alt="image" src="https://github.com/dagu-dev/dagu/assets/1026584/1c126878-00c8-4860-aa46-33d9a86bd693">

With a small adjustment to your yaml:

```
params: "ARG1=VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER_VERY_VERY_LONG_PARAMETER"
steps:
  - name: step1
    command: echo hello
```
