### ISSUE TITLE
Docker executor does not propagate exit code

### ISSUE THREAD

**Issue by x4204** [dagu-dev/dagu#610]
Failed commands from docker executor are not reported as "failed"

Example DAG:
```yaml
steps:
  - name: 'emulate-failure'
    command: ['false']
    executor:
      type: 'docker'
      config:
        image: 'ubuntu:24.04'
        host:
          AutoRemove: true
```

#### Expectation

The step is reported as `failed`:
![image](https://github.com/user-attachments/assets/2c291ad6-6b9a-4859-a1d4-69cc8df41f3d)

#### Actual

The step is reported as `finished`:
![image](https://github.com/user-attachments/assets/6ff31d86-b235-482c-934f-d3ec62aee7d4)
