### ISSUE TITLE
Docker executor does not propagate stderr output

### ISSUE THREAD

**Issue by x4204** [dagu-dev/dagu#611]
Output from stderr does not appear in step logs

Example DAG:
```yaml
steps:
  - name: 'run'
    command: ['run']
    executor:
      type: 'docker'
      config:
        image: 'ubuntu:24.04'
        host:
          AutoRemove: true
          Binds:
            - '/tmp/run:/usr/bin/run'
```
Script `/tmp/run`:
```sh
#!/bin/sh

echo '<message to stdout>'
echo '<message to stderr>' 1>&2
```

#### Expectation

Stderr output appears in step logs:
![image](https://github.com/user-attachments/assets/b0df65ae-3071-4cf0-a33f-6fda0842b509)

#### Actual

Stderr output does not appear in step logs:
![image](https://github.com/user-attachments/assets/1627c442-7458-4873-9123-de4c09230ff0)
